on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-failed.yml'

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo Build failed...
          exit 1
