on:
  push:
    branches:
      - nop

name: No operation

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: No operation
        run: |
          echo This should not be displayed
